apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reports-claim
  namespace: production
spec:
  storageClassName: "local-storage"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi